{% set name = "sparselt" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LiamBindle/sparselt/archive/{{ version }}.tar.gz
  sha256: d39a3aad3084ffd79af65b1d457488173e5c31aba3f878bf999419b39947a963

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - netcdf4
    - numpy
    - python >={{ python_min }}
    - scipy
    - xarray

test:
  imports:
    - sparselt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LiamBindle/sparselt
  license: MIT
  license_file:
    - LICENSE
  summary: A small library for regridding Earth system data with vectorized sparse linear transforms.

extra:
  recipe-maintainers:
    - LiamBindle
